[Feat] Component TitMain 생성
9oormthonUNIV-3th-KGU/fe-kakao-clone pull request #9
Opened 2024-09-06 13:06 UTC by gmlwlsdl

## #️⃣연관된 이슈

> [Feat] Component TitMain 생성

## 📝작업 내용

> /src/index.css 생성 후 카카오 폰트를 전역적으로 적용하였습니다.
> 각 페이지에 쓰일 TitMain 컴포넌트를 제작하였습니다.
> 'url' prop에는 해당 div의 background-image 적용해서 사용하시면 됩니다.

### 스크린샷 (선택)
> <img width="484" alt="image" src="https://github.com/user-attachments/assets/0460dd90-6a04-4c3a-b184-a3e8d087dc4f">

## 💬리뷰 요구사항(선택)

> 많은 페이지에 공통적으로 사용되는 컴포넌트라, 빠르게 만들어 올렸습니다! 🙇‍♀️

2024-09-07 03:19 UTC, wontory requested changes
컴포넌트명은 길어도 괜찮아요.
뭔가를 줄여쓰는 것은 좋은 패턴은 아니라고 생각합니다!

2024-09-07 03:19 UTC, wontory commented on src/components/ContItem.tsx
> +      <Cont>
단어를 줄여 쓰는 것은 읽는 사람으로 하여금 뜻을 한번 더 생각하게 하기 때문에 최대한 풀네임으로 작성해주세요!

2024-09-07 03:19 UTC, wontory commented on src/components/ContItem.tsx
> +        <TxtItem dangerouslySetInnerHTML={{ __html: txt }} />
Tit -> TitleItem
Txt 정도는 보편적으로 쓰이기 때문에 괜찮은 것 같습니다.

2024-09-07 03:19 UTC, wontory commented on src/components/ContItem.tsx
> +        <DescItem dangerouslySetInnerHTML={{ __html: desc }} />
dangerouslySetInnerHTML을 사용하신 이유가 따로 있으신가요?

2024-09-07 03:19 UTC, wontory commented on src/components/ContItem.tsx
> +        <WrapLogo href={img} target="_blank" rel="noopener noreferrer">
WrapLogo라는 컴포넌트명만 보고는 이 요소가 a 요소인지 알 수 없어요.
이미지는 img 태그로, 로고에 링크가 필요하면 이미지를 a로 감싸주는 것이 더 좋은 것 같아요!

2024-09-07 03:19 UTC, wontory commented on src/components/OutlinkBtn.tsx
> +}
컴포넌트명은 Btn인데 코드를 보면 Btn의 역할을 수행하고 있지 않아요!

2024-09-07 03:19 UTC, wontory commented on src/components/WrapCommunity.tsx
> +            </Li>
반복적인 패턴은 데이터를 따로 배열로 빼고 map으로 렌더링할 수 있어요.
```tsx
const contents = [{ title: 카카오, text: '사람을 이해하는 기술로, ...', description: '카카오는 사람에 대한 이해를 바탕으로 ...', image: 'https://careers...', link: 'https://t1.kakaocdn...' }, ...]

...

contents.map(({title, text, description, image, link}) => (
  <li>
    <ContentItem
      title={title}
      text={text}
      description={description}
      image={image}
      link={link} />
  </li>
))
```

2024-09-07 03:19 UTC, wontory commented on src/main.tsx
> +  { path: '/about/subsidiaryCompany', element: <SubsidiaryCompany /> },
```ts
{
  path: "/page-a",
  element: <PageA/>,
  // children에 중첩라우팅을 배열로 추가합니다.
  children: [
    {
      path: "Children-1",
      element: <Children1/>,
    },
    {
      path: "Children-2",
      element: <Children2/>,
    },
  ],
},
```

2024-09-07 07:11 UTC, gmlwlsdl commented on src/components/ContItem.tsx
> +        <DescItem dangerouslySetInnerHTML={{ __html: desc }} />
WrapCommunity.tsx에서 `txt`와 `desc`을 받아올 때, 문장 간 <br /> 처리를 해주어야 하는 부분이 있어 위 방법을 사용하였습니다!

2024-09-07 07:11 UTC, gmlwlsdl commented on src/components/ContItem.tsx
> +      <Cont>
네 알겠습니다!

2024-09-07 07:12 UTC, gmlwlsdl commented on src/components/ContItem.tsx
> +        <WrapLogo href={img} target="_blank" rel="noopener noreferrer">
아하 넵 알겠습니다!

2024-09-07 07:14 UTC, gmlwlsdl commented on src/components/OutlinkBtn.tsx
> +}
넵 수정하도록 하겠습니다

2024-09-07 07:15 UTC, gmlwlsdl commented on src/components/WrapCommunity.tsx
> +            </Li>
넵 적용하도록 하겠습니다!

2024-09-07 07:16 UTC, gmlwlsdl commented on src/main.tsx
> +  { path: '/about/subsidiaryCompany', element: <SubsidiaryCompany /> },
중첩라우팅 적용하겠습니다!

2024-09-07 07:18 UTC, wontory commented on src/components/WrapCommunity.tsx
> +            </Li>
배열로 옮기시면서 desc 자료구조를 고민해보시면 위에서 이야기했던 dangerouslySetInnerHTML도 없앨 수 있을 것 같습니다~

2024-09-07 13:59 UTC, boroboro01 approved these changes

2024-09-15 09:21 UTC, wontory approved these changes
LGTM

2024-09-15 09:22 UTC, merged